name: publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u tunguska-cc --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}

